name: Sky-Fly
version: '${project.version}'
main: top.skyliey.skyfly.Sky_Fly
author: Monostar14
api-version: '1.20'

commands:
  fly:
    description: Sky-Fly command.
    usage: /fly <true|false>
    permission: skyfly.fly
  flyspeed:
    description: Sky-Fly command.
    usage: /flyspeed <speed>
    permission: skyfly.flyspeed
  flypower:
    description: Sky-Fly command.
    usage: /flypower <power>
    permission: skyfly.flypower

permissions:
  skyfly.fly:
    description: Allows the player to use the /fly command.
    default: op
  skyfly.flyspeed:
    description: Allows the player to use the /flyspeed command.
    default: op
  skyfly.flypower:
    description: Allows the player to use the /flypower command.
    default: op





