name: Sky-Fly
version: '${project.version}'
main: top.skyliey.skyfly.Sky_Fly
author: Monostar14
api-version: '1.20'

commands:
  fly:
    description: Sky-Fly command.
    usage: /skyfly <true|false>
    permission: skyfly.fly

